apiVersion: v1
kind: Secret
metadata:
  name: manifest-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ReadTheory/manifest.git
  password: {{ .Values.token }}
  username: ReadTheory
  insecure: "true" 
  forceHttpBasicAuth: "true" 
  enableLfs: "true" 

---

apiVersion: v1
kind: Secret
metadata:
  name: argo-apps-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ReadTheory/argo-apps.git
  password: {{ .Values.token }}
  username: ReadTheory
  insecure: "true" 
  forceHttpBasicAuth: "true" 
  enableLfs: "true" 